### ISSUE TITLE
Bug on update notifier, lxqt, while dragging window

### ISSUE THREAD

**Issue by terremoth** [lubuntu-team/lubuntu-update-notifier#1] opened 2020-08-26 04:38 UTC
I opened this issue on: https://github.com/lxqt/lxqt/issues/1838#event-3684894055

But the responsible there said that has nothing to do with lxqt itself issue. So I think this can be a better place to open this issue. If not, PLEASE, where EXACTLY should I open this issue?

**Comment by stefonarch** [comment] 2020-08-30 09:39
I can confirm the same issue on VM using Lubuntu 20.04
![schermata-30-11-39-20](https://user-images.githubusercontent.com/10681413/91656009-74eeab00-eab5-11ea-81e4-11168c7070a3.png)


Trying to close the update-norifier window  it's not responding.

**Comment by FuRuYa7** [comment] 2021-01-20 18:01
#### Only the display of the "Update Notifier" window is strange.

It also occurs in **Lubuntu 20.10** . If the "Full Upgrade" window finishes normally, the "Update Notifier" window also closes and disappears. So you don't have to worry about it.

Pass not only the "Full Upgrade" window, but another window to the "Update Notifier" window. The trail remains only in the "Update Notifier" window. 

Even if the position of the button on the title bar is misaligned, it may not be displayed properly and you may not be able to operate it. Click the "Update Notifier" app in the panel bar to iconify and restore to restore the window title bar. However, the display inside the window is not normal.

**Comment by comp-phys-marc** [comment] 2023-01-15 03:41
I can confirm that I am seeing this same behaviour on Lubuntu 22.04.

```
marcuse@redblue:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```

![FmXp8WxXkBkQwHm](https://user-images.githubusercontent.com/94946848/212521855-27f80c10-8dd7-4b00-a666-77bc76af31ee.jpeg)

**Comment by terremoth** [comment] 2023-01-16 00:50
I wish I could solve this alone. I will try to contact ubuntu devs and try to open a launchpad bug issue there

**Comment by monetaryabyss** [comment] 2023-01-16 00:57
This looks like something that could happen if the compositor is not running. Is Compton or Picom running?

**Comment by tsimonq2** [comment] 2023-11-29 22:31
I fixed this pretty recently, it was running in a single thread. Created a child process for the popup window and it's all fixed now. Should be landing via SRU sometime soon.

**Closed as completed by tsimonq2** 2023-11-29 22:31 UTC

**Comment by terremoth** [comment] 2023-11-30 00:55
> I fixed this pretty recently, it was running in a single thread. Created a child process for the popup window and it's all fixed now. Should be landing via SRU sometime soon.

awesome, thanks!
